#!/usr/bin/env python3
"""
Builds a single self-contained scratch-org-creator.sh from the source files.
Run: python3 build-installer.py
"""

import base64
import hashlib
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
UI_DIR = SCRIPT_DIR / "scratch-org-ui"

FILES_TO_EMBED = {
    "app.py": UI_DIR / "app.py",
    "features.json": UI_DIR / "features.json",
    "settings.json": UI_DIR / "settings.json",
    "templates/index.html": UI_DIR / "templates" / "index.html",
}

OUTPUT = SCRIPT_DIR / "scratch-org-creator.sh"


def file_hash(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()[:16]


def build():
    payloads: dict[str, str] = {}
    total_raw = 0
    for name, path in FILES_TO_EMBED.items():
        raw = path.read_bytes()
        total_raw += len(raw)
        payloads[name] = base64.b64encode(raw).decode()

    combined_hash = file_hash(
        b"".join(p.read_bytes() for p in FILES_TO_EMBED.values())
    )

    shell_header = f'''\
#!/usr/bin/env bash
#
# scratch-org-creator.sh  —  Self-contained Scratch Org Creator
#
# This single file bundles the Flask web app, 296-feature catalog,
# settings catalog, and the full HTML UI.  Just run it.
#
# Prerequisites:
#   - python3  (pre-installed on macOS; apt install python3 on Linux)
#   - sf CLI   (https://developer.salesforce.com/tools/salesforcecli)
#   - A Salesforce Dev Hub org
#
# Usage:
#   bash scratch-org-creator.sh            # launch web UI
#   bash scratch-org-creator.sh --update   # force re-extract bundled files
#   bash scratch-org-creator.sh --help     # show help
#
# Generated by build-installer.py — do not hand-edit.

set -u
set -o pipefail

# ── pretty output ──────────────────────────────────────────────
BOLD=$'\\033[1m'; DIM=$'\\033[2m'; RESET=$'\\033[0m'
GREEN=$'\\033[32m'; CYAN=$'\\033[36m'; YELLOW=$'\\033[33m'; RED=$'\\033[31m'

say()  {{ printf "%s\\n" "$*"; }}
info() {{ printf "%s[i]%s %s\\n" "$CYAN" "$RESET" "$*"; }}
ok()   {{ printf "%s[✓]%s %s\\n" "$GREEN" "$RESET" "$*"; }}
warn() {{ printf "%s[!]%s %s\\n" "$YELLOW" "$RESET" "$*"; }}
err()  {{ printf "%s[x]%s %s\\n" "$RED" "$RESET" "$*" 1>&2; }}

# ── configuration ──────────────────────────────────────────────
INSTALL_DIR="${{HOME}}/.scratch-org-creator"
BUNDLE_VERSION="{combined_hash}"

# ── argument parsing ───────────────────────────────────────────
FORCE_UPDATE=false
for arg in "$@"; do
  case "$arg" in
    --update) FORCE_UPDATE=true ;;
    -h|--help)
      say "${{BOLD}}Scratch Org Creator${{RESET}} — interactive web UI for Salesforce scratch orgs"
      say ""
      say "Usage: bash scratch-org-creator.sh [OPTIONS]"
      say ""
      say "Options:"
      say "  --update   Force re-extract of bundled files"
      say "  --help     Show this help message"
      say ""
      say "Prerequisites:"
      say "  python3    Pre-installed on macOS; apt install python3 on Linux"
      say "  sf CLI     https://developer.salesforce.com/tools/salesforcecli"
      exit 0 ;;
  esac
done

# ── prerequisite checks ───────────────────────────────────────
if ! command -v python3 >/dev/null 2>&1; then
  err "python3 is required but not found."
  say "  macOS:  comes pre-installed"
  say "  Linux:  sudo apt install python3 python3-pip"
  exit 1
fi

if ! command -v sf >/dev/null 2>&1; then
  err "Salesforce CLI (sf) is not installed."
  say "  Install: npm install -g @salesforce/cli"
  say "  Docs:    https://developer.salesforce.com/tools/salesforcecli"
  exit 1
fi

# ── extract embedded files ─────────────────────────────────────
needs_extract() {{
  [ "$FORCE_UPDATE" = true ] && return 0
  [ ! -f "$INSTALL_DIR/.version" ] && return 0
  [ "$(cat "$INSTALL_DIR/.version" 2>/dev/null)" != "$BUNDLE_VERSION" ] && return 0
  [ ! -f "$INSTALL_DIR/app.py" ] && return 0
  return 1
}}

extract_files() {{
  info "Extracting bundled files to $INSTALL_DIR ..."
  mkdir -p "$INSTALL_DIR/templates"

'''

    shell_footer = '''\

  printf "%s" "$BUNDLE_VERSION" > "$INSTALL_DIR/.version"
  ok "Files extracted (version $BUNDLE_VERSION)."
}

if needs_extract; then
  extract_files
fi

# ── ensure Flask is installed ──────────────────────────────────
VENDOR_PATH="$INSTALL_DIR/vendor"
if ! python3 -c "import sys; sys.path.insert(0,'$VENDOR_PATH'); import flask" 2>/dev/null; then
  info "Installing Flask (one-time setup)..."
  mkdir -p "$VENDOR_PATH"
  if pip3 install --quiet --target "$VENDOR_PATH" flask 2>/dev/null; then
    ok "Flask installed to $VENDOR_PATH"
  elif python3 -m pip install --quiet --target "$VENDOR_PATH" flask 2>/dev/null; then
    ok "Flask installed to $VENDOR_PATH"
  else
    err "Could not install Flask automatically."
    say "  Please run:  pip3 install flask"
    exit 1
  fi
fi

# ── launch ─────────────────────────────────────────────────────
PREFERRED_PORT=8484
PORT=$(python3 -c "
import socket
preferred = $PREFERRED_PORT
try:
    s = socket.socket()
    s.bind(('', preferred))
    s.close()
    print(preferred)
except OSError:
    s = socket.socket()
    s.bind(('', 0))
    print(s.getsockname()[1])
    s.close()
")

say ""
say "${BOLD}╔══════════════════════════════════════╗${RESET}"
say "${BOLD}║      Scratch Org Creator  v1.0       ║${RESET}"
say "${BOLD}╚══════════════════════════════════════╝${RESET}"
say ""
info "Starting web server on http://localhost:$PORT ..."

python3 "$INSTALL_DIR/app.py" "$PORT" &
SERVER_PID=$!
sleep 1

if ! kill -0 "$SERVER_PID" 2>/dev/null; then
  err "Server failed to start. Check that port $PORT is available."
  exit 1
fi

ok "Web UI running at: ${BOLD}http://localhost:$PORT${RESET}"
say ""

URL="http://localhost:$PORT"
if command -v open >/dev/null 2>&1; then
  open "$URL"
elif command -v xdg-open >/dev/null 2>&1; then
  xdg-open "$URL"
elif command -v wslview >/dev/null 2>&1; then
  wslview "$URL"
else
  say "Open this URL in your browser: $URL"
fi

say "${DIM}Press Ctrl+C to stop the server when done.${RESET}"
say ""

trap "kill $SERVER_PID 2>/dev/null; exit 0" INT TERM
wait "$SERVER_PID" 2>/dev/null
'''

    extraction_lines = []
    for dest_name, b64_data in payloads.items():
        dest_path = f"$INSTALL_DIR/{dest_name}"
        marker = f"__EOF_{dest_name.replace('/', '_').replace('.', '_').upper()}__"
        extraction_lines.append(f"  python3 -c \"import base64,sys; sys.stdout.buffer.write(base64.b64decode(sys.stdin.read()))\" <<'{marker}' > \"{dest_path}\"")
        extraction_lines.append(b64_data)
        extraction_lines.append(marker)
        extraction_lines.append("")

    full_script = shell_header + "\n".join(extraction_lines) + "\n" + shell_footer

    OUTPUT.write_text(full_script)
    OUTPUT.chmod(0o755)

    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Built: {OUTPUT}")
    print(f"Size:  {size_kb:.0f} KB ({total_raw / 1024:.0f} KB raw -> {sum(len(v) for v in payloads.values()) / 1024:.0f} KB base64)")
    print(f"Hash:  {combined_hash}")


if __name__ == "__main__":
    build()
