#!/usr/bin/env python3
"""
Builds self-contained installers from the source files:
  - scratch-org-creator.sh   (macOS / Linux)
  - scratch-org-creator.bat  (Windows)

Run: python3 build-installer.py
"""

import base64
import hashlib
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
UI_DIR = SCRIPT_DIR / "scratch-org-ui"

FILES_TO_EMBED = {
    "app.py": UI_DIR / "app.py",
    "features.json": UI_DIR / "features.json",
    "settings.json": UI_DIR / "settings.json",
    "templates/index.html": UI_DIR / "templates" / "index.html",
}

OUTPUT_SH = SCRIPT_DIR / "scratch-org-creator.sh"
OUTPUT_BAT = SCRIPT_DIR / "scratch-org-creator.bat"


def file_hash(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()[:16]


def build():
    payloads: dict[str, str] = {}
    total_raw = 0
    for name, path in FILES_TO_EMBED.items():
        raw = path.read_bytes()
        total_raw += len(raw)
        payloads[name] = base64.b64encode(raw).decode()

    combined_hash = file_hash(
        b"".join(p.read_bytes() for p in FILES_TO_EMBED.values())
    )

    build_sh(payloads, combined_hash, total_raw)
    build_bat(payloads, combined_hash, total_raw)


def build_sh(payloads, combined_hash, total_raw):

    shell_header = f'''\
#!/usr/bin/env bash
#
# scratch-org-creator.sh  —  Self-contained Scratch Org Creator
#
# This single file bundles the Flask web app, 296-feature catalog,
# settings catalog, and the full HTML UI.  Just run it.
#
# Prerequisites:
#   - python3  (pre-installed on macOS; apt install python3 on Linux)
#   - sf CLI   (https://developer.salesforce.com/tools/salesforcecli)
#   - A Salesforce Dev Hub org
#
# Usage:
#   bash scratch-org-creator.sh            # launch web UI
#   bash scratch-org-creator.sh --update   # force re-extract bundled files
#   bash scratch-org-creator.sh --help     # show help
#
# Generated by build-installer.py — do not hand-edit.

set -u
set -o pipefail

# ── pretty output ──────────────────────────────────────────────
BOLD=$'\\033[1m'; DIM=$'\\033[2m'; RESET=$'\\033[0m'
GREEN=$'\\033[32m'; CYAN=$'\\033[36m'; YELLOW=$'\\033[33m'; RED=$'\\033[31m'

say()  {{ printf "%s\\n" "$*"; }}
info() {{ printf "%s[i]%s %s\\n" "$CYAN" "$RESET" "$*"; }}
ok()   {{ printf "%s[✓]%s %s\\n" "$GREEN" "$RESET" "$*"; }}
warn() {{ printf "%s[!]%s %s\\n" "$YELLOW" "$RESET" "$*"; }}
err()  {{ printf "%s[x]%s %s\\n" "$RED" "$RESET" "$*" 1>&2; }}

# ── configuration ──────────────────────────────────────────────
INSTALL_DIR="${{HOME}}/.scratch-org-creator"
BUNDLE_VERSION="{combined_hash}"

# ── argument parsing ───────────────────────────────────────────
FORCE_UPDATE=false
for arg in "$@"; do
  case "$arg" in
    --update) FORCE_UPDATE=true ;;
    -h|--help)
      say "${{BOLD}}Scratch Org Creator${{RESET}} — interactive web UI for Salesforce scratch orgs"
      say ""
      say "Usage: bash scratch-org-creator.sh [OPTIONS]"
      say ""
      say "Options:"
      say "  --update   Force re-extract of bundled files"
      say "  --help     Show this help message"
      say ""
      say "Prerequisites:"
      say "  python3    Pre-installed on macOS; apt install python3 on Linux"
      say "  sf CLI     https://developer.salesforce.com/tools/salesforcecli"
      exit 0 ;;
  esac
done

# ── prerequisite checks ───────────────────────────────────────
if ! command -v python3 >/dev/null 2>&1; then
  err "python3 is required but not found."
  say "  macOS:  comes pre-installed"
  say "  Linux:  sudo apt install python3 python3-pip"
  exit 1
fi

if ! command -v sf >/dev/null 2>&1; then
  err "Salesforce CLI (sf) is not installed."
  say "  Install: npm install -g @salesforce/cli"
  say "  Docs:    https://developer.salesforce.com/tools/salesforcecli"
  exit 1
fi

# ── extract embedded files ─────────────────────────────────────
needs_extract() {{
  [ "$FORCE_UPDATE" = true ] && return 0
  [ ! -f "$INSTALL_DIR/.version" ] && return 0
  [ "$(cat "$INSTALL_DIR/.version" 2>/dev/null)" != "$BUNDLE_VERSION" ] && return 0
  [ ! -f "$INSTALL_DIR/app.py" ] && return 0
  return 1
}}

extract_files() {{
  info "Extracting bundled files to $INSTALL_DIR ..."
  mkdir -p "$INSTALL_DIR/templates"

'''

    shell_footer = '''\

  printf "%s" "$BUNDLE_VERSION" > "$INSTALL_DIR/.version"
  ok "Files extracted (version $BUNDLE_VERSION)."
}

if needs_extract; then
  extract_files
fi

# ── ensure Flask is installed ──────────────────────────────────
VENDOR_PATH="$INSTALL_DIR/vendor"
if ! python3 -c "import sys; sys.path.insert(0,'$VENDOR_PATH'); import flask" 2>/dev/null; then
  info "Installing Flask (one-time setup)..."
  mkdir -p "$VENDOR_PATH"
  if pip3 install --quiet --target "$VENDOR_PATH" flask 2>/dev/null; then
    ok "Flask installed to $VENDOR_PATH"
  elif python3 -m pip install --quiet --target "$VENDOR_PATH" flask 2>/dev/null; then
    ok "Flask installed to $VENDOR_PATH"
  else
    err "Could not install Flask automatically."
    say "  Please run:  pip3 install flask"
    exit 1
  fi
fi

# ── launch ─────────────────────────────────────────────────────
PREFERRED_PORT=8484
PORT=$(python3 -c "
import socket
preferred = $PREFERRED_PORT
try:
    s = socket.socket()
    s.bind(('', preferred))
    s.close()
    print(preferred)
except OSError:
    s = socket.socket()
    s.bind(('', 0))
    print(s.getsockname()[1])
    s.close()
")

say ""
say "${BOLD}╔══════════════════════════════════════╗${RESET}"
say "${BOLD}║      Scratch Org Creator  v1.0       ║${RESET}"
say "${BOLD}╚══════════════════════════════════════╝${RESET}"
say ""
info "Starting web server on http://localhost:$PORT ..."

python3 "$INSTALL_DIR/app.py" "$PORT" &
SERVER_PID=$!
sleep 1

if ! kill -0 "$SERVER_PID" 2>/dev/null; then
  err "Server failed to start. Check that port $PORT is available."
  exit 1
fi

ok "Web UI running at: ${BOLD}http://localhost:$PORT${RESET}"
say ""

URL="http://localhost:$PORT"
if command -v open >/dev/null 2>&1; then
  open "$URL"
elif command -v xdg-open >/dev/null 2>&1; then
  xdg-open "$URL"
elif command -v wslview >/dev/null 2>&1; then
  wslview "$URL"
else
  say "Open this URL in your browser: $URL"
fi

say "${DIM}Press Ctrl+C to stop the server when done.${RESET}"
say ""

trap "kill $SERVER_PID 2>/dev/null; exit 0" INT TERM
wait "$SERVER_PID" 2>/dev/null
'''

    extraction_lines = []
    for dest_name, b64_data in payloads.items():
        dest_path = f"$INSTALL_DIR/{dest_name}"
        marker = f"__EOF_{dest_name.replace('/', '_').replace('.', '_').upper()}__"
        extraction_lines.append(f"  python3 -c \"import base64,sys; sys.stdout.buffer.write(base64.b64decode(sys.stdin.read()))\" <<'{marker}' > \"{dest_path}\"")
        extraction_lines.append(b64_data)
        extraction_lines.append(marker)
        extraction_lines.append("")

    full_script = shell_header + "\n".join(extraction_lines) + "\n" + shell_footer

    OUTPUT_SH.write_text(full_script)
    OUTPUT_SH.chmod(0o755)

    size_kb = OUTPUT_SH.stat().st_size / 1024
    print(f"Built: {OUTPUT_SH}")
    print(f"Size:  {size_kb:.0f} KB ({total_raw / 1024:.0f} KB raw -> {sum(len(v) for v in payloads.values()) / 1024:.0f} KB base64)")
    print(f"Hash:  {combined_hash}")


def build_bat(payloads, combined_hash, total_raw):
    """Build the Windows .bat self-contained installer + companion data file."""

    # Build the companion Python extraction script with embedded base64 data
    extraction_py_lines = []
    for dest_name, b64_data in payloads.items():
        extraction_py_lines.append(f'    "{dest_name}": "{b64_data}",')

    extraction_py = "\n".join(extraction_py_lines)

    extraction_script = f'''import os, base64, sys

install_dir = os.path.join(os.path.expanduser("~"), ".scratch-org-creator")
os.makedirs(os.path.join(install_dir, "templates"), exist_ok=True)

files = {{
{extraction_py}
}}

for name, data in files.items():
    filepath = os.path.join(install_dir, name.replace("/", os.sep))
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "wb") as f:
        f.write(base64.b64decode(data))

with open(os.path.join(install_dir, ".version"), "w") as f:
    f.write("{combined_hash}")

print("[OK] Files extracted.")
'''

    data_py_path = SCRIPT_DIR / "scratch-org-creator-data.py"
    data_py_path.write_text(extraction_script, encoding="utf-8")

    # Build the .bat launcher
    bat_content = f'''@echo off
setlocal enabledelayedexpansion

:: scratch-org-creator.bat — Self-contained Scratch Org Creator for Windows
::
:: Distribute this file alongside scratch-org-creator-data.py.
:: Both files must be in the same folder.
::
:: Prerequisites:
::   - Python 3  (https://www.python.org/downloads/)
::   - sf CLI    (https://developer.salesforce.com/tools/salesforcecli)
::   - A Salesforce Dev Hub org
::
:: Usage:
::   scratch-org-creator.bat            Launch web UI
::   scratch-org-creator.bat --update   Force re-extract bundled files
::   scratch-org-creator.bat --help     Show help
::
:: Generated by build-installer.py — do not hand-edit.

title Scratch Org Creator

:: ── Argument parsing ─────────────────────────────────────────
if "%~1"=="--help" goto :show_help
if "%~1"=="-h" goto :show_help
set "FORCE_UPDATE=0"
if "%~1"=="--update" set "FORCE_UPDATE=1"
goto :main

:show_help
echo.
echo   Scratch Org Creator — Interactive Web UI for Salesforce Scratch Orgs
echo.
echo   Usage:  scratch-org-creator.bat [OPTIONS]
echo.
echo   Options:
echo     --update   Force re-extract of bundled files
echo     --help     Show this help message
echo.
echo   Prerequisites:
echo     Python 3   https://www.python.org/downloads/
echo     sf CLI     https://developer.salesforce.com/tools/salesforcecli
echo.
exit /b 0

:main
echo.
echo  ======================================
echo       Scratch Org Creator  v1.0
echo  ======================================
echo.

:: ── Detect Python ────────────────────────────────────────────
set "PYTHON_CMD="

where python3 >nul 2>&1
if %errorlevel%==0 (
    set "PYTHON_CMD=python3"
    goto :python_found
)

where python >nul 2>&1
if %errorlevel%==0 (
    for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set "PY_VER=%%v"
    if "!PY_VER:~0,1!"=="3" (
        set "PYTHON_CMD=python"
        goto :python_found
    ) else (
        echo [x] Python found but it is version !PY_VER! — Python 3 is required.
        echo     Download from: https://www.python.org/downloads/
        echo     Make sure to check "Add Python to PATH" during installation.
        pause
        exit /b 1
    )
)

echo [x] Python 3 is not installed or not on PATH.
echo     Download from: https://www.python.org/downloads/
echo     Make sure to check "Add Python to PATH" during installation.
pause
exit /b 1

:python_found
for /f "delims=" %%v in ('!PYTHON_CMD! --version 2^>^&1') do set "PY_VERSION=%%v"
echo [OK] %PY_VERSION%

:: ── Check Salesforce CLI ─────────────────────────────────────
where sf >nul 2>&1
if %errorlevel% neq 0 (
    echo [x] Salesforce CLI ^(sf^) is not installed or not on PATH.
    echo     Install: npm install -g @salesforce/cli
    echo     Docs:    https://developer.salesforce.com/tools/salesforcecli
    pause
    exit /b 1
)
for /f "delims=" %%v in ('sf --version 2^>^&1') do (
    set "SF_VERSION=%%v"
    goto :sf_done
)
:sf_done
echo [OK] sf CLI: %SF_VERSION%

:: ── Configuration ────────────────────────────────────────────
set "INSTALL_DIR=%USERPROFILE%\\.scratch-org-creator"
set "BUNDLE_VERSION={combined_hash}"
set "VENDOR_PATH=%INSTALL_DIR%\\vendor"

:: ── Extract bundled files using companion data script ────────
set "NEEDS_EXTRACT=0"
if "%FORCE_UPDATE%"=="1" set "NEEDS_EXTRACT=1"
if not exist "%INSTALL_DIR%\\.version" set "NEEDS_EXTRACT=1"
if not exist "%INSTALL_DIR%\\app.py" set "NEEDS_EXTRACT=1"

if "%NEEDS_EXTRACT%"=="0" (
    set /p CURRENT_VER=<"%INSTALL_DIR%\\.version"
    if not "!CURRENT_VER!"=="%BUNDLE_VERSION%" set "NEEDS_EXTRACT=1"
)

if "%NEEDS_EXTRACT%"=="1" (
    echo [i] Extracting bundled files to %INSTALL_DIR% ...
    !PYTHON_CMD! "%~dp0scratch-org-creator-data.py"
    if !errorlevel! neq 0 (
        echo [x] Failed to extract files. Make sure scratch-org-creator-data.py is
        echo     in the same folder as this .bat file.
        pause
        exit /b 1
    )
) else (
    echo [OK] Files up to date ^(version %BUNDLE_VERSION:~0,8%...^)
)

:: ── Ensure Flask is installed ────────────────────────────────
!PYTHON_CMD! -c "import sys; sys.path.insert(0, r'%VENDOR_PATH%'); import flask" >nul 2>&1
if %errorlevel% neq 0 (
    echo [i] Installing Flask ^(one-time setup^)...
    if not exist "%VENDOR_PATH%" mkdir "%VENDOR_PATH%"
    !PYTHON_CMD! -m pip install --quiet --target "%VENDOR_PATH%" flask >nul 2>&1
    if !errorlevel!==0 (
        echo [OK] Flask installed.
    ) else (
        echo [x] Could not install Flask automatically.
        echo     Please run:  pip install flask
        pause
        exit /b 1
    )
) else (
    echo [OK] Flask available
)

:: ── Find available port ──────────────────────────────────────
for /f "delims=" %%p in ('!PYTHON_CMD! -c "import socket;s=socket.socket();exec('try:\\n s.bind((chr(39)+chr(39),8484));s.close();print(8484)\\nexcept OSError:\\n s2=socket.socket();s2.bind((chr(39)+chr(39),0));print(s2.getsockname()[1]);s2.close()')"') do set "PORT=%%p"
if not defined PORT set "PORT=8484"

:: ── Launch Flask server ──────────────────────────────────────
echo.
echo [i] Starting web server on http://localhost:%PORT% ...
start /b "" !PYTHON_CMD! "%INSTALL_DIR%\\app.py" %PORT%

:: Give server a moment to start
!PYTHON_CMD! -c "import time; time.sleep(1.5)"

echo [OK] Web UI running at: http://localhost:%PORT%
echo.

:: ── Open browser ─────────────────────────────────────────────
start "" "http://localhost:%PORT%"

echo  ─────────────────────────────────────────────────────────
echo    The Scratch Org Creator is open in your browser.
echo.
echo    Press any key to stop the server and exit.
echo  ─────────────────────────────────────────────────────────
echo.

pause >nul

:: ── Cleanup ──────────────────────────────────────────────────
for /f "tokens=5" %%a in ('netstat -aon ^| findstr ":%PORT%.*LISTENING"') do (
    taskkill /F /PID %%a >nul 2>&1
)

echo.
echo [OK] Server stopped. Goodbye!
exit /b 0
'''

    OUTPUT_BAT.write_text(bat_content, encoding="utf-8")

    size_kb = OUTPUT_BAT.stat().st_size / 1024
    data_kb = data_py_path.stat().st_size / 1024
    print(f"Built: {OUTPUT_BAT} ({size_kb:.0f} KB)")
    print(f"Built: {data_py_path} ({data_kb:.0f} KB)")


if __name__ == "__main__":
    build()
